# Config file for pytest

# Official header for pytest.ini
[pytest]
# async fixtures and tests are handled automatically without @pytest.mark.asyncio
asyncio_mode = auto
# Location of app
pythonpath = .
# Shows tests folder
testpaths = ./tests
# Files only that starts with test_
python_files = test_*.py
# Only functions that start with test_
python_functions = test_*
# Additional options
# v (verbose) - more details while running tests
# strict-markers - Python will alert about using unregistered marker
# tb=short - traceback for error, short version
addopts =
    -v
    --strict-markers 
    --tb=short
    --cov=app
    --cov-report=term-missing
    --cov-fail-under=80 

# Section for registering markers
markers = 
    auth: users authentication endpoints test
    business: business validation endpoints test
    services: test for services
    status: test for status endpoints
    validators: test for validators