"""adding api_key field to User model

Revision ID: 184af7bb01e6
Revises: 89584fa91db7
Create Date: 2026-02-20 11:20:24.738672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184af7bb01e6'
down_revision: Union[str, Sequence[str], None] = '89584fa91db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key_hashed', sa.String(), nullable=True))
    op.add_column('users', sa.Column('api_key_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.create_index(op.f('ix_users_api_key_hashed'), 'users', ['api_key_hashed'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_key_hashed'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('users', 'api_key_created_at')
    op.drop_column('users', 'api_key_hashed')
    # ### end Alembic commands ###
